# Site settings
author: Kevin Malin
title: Take me Out to the Ballgame
header-img: img/home-bg.png
email: racmalin@yahoo.com
copyright_name: Kevin Malin
description: > # this means to ignore newlines until "baseurl:"
  It's almost retirement time!!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  racmalin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
